name: in1910-book
channels:
  - default
  - conda-forge
dependencies:
  - python
  - sphinx
  - pip
  - mypy
  - black
  - flake8
  - matplotlib
  - pandas
  - numpy
  - numba
  - scipy
  - cython
  - line_profiler
  - pybind11
  - dask
  - cppyy
  - cmake
  - ffmpeg
  - jupyter
  - jupyterlab
  - jupyter-book
  - sphinx-inline-tabs
