name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: finsberg/in1910
    steps:
      - uses: actions/checkout@v2

      - name: Build docs
        run: |
          make docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/html

      - name: Deploy to github pages at UiO
        uses: cpina/github-action-push-to-another-repository@devel
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: ./book/_build/html
          destination-github-username: 'IN1910'
          destination-repository-name: 'IN1910_H22'
          github-server: github.uio.no
          user-email: henriknf@simula.no
          commit-message: Publish docs
          target-branch: gh-pages
